import type { Config } from 'tailwindcss';

export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  safelist: [
    'bg-surface',
    'text-on-surface',
    'font-body-md',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        'primary-fixed': '#d9e2ff',
        'primary-container': '#0f52ba',
        'tertiary-fixed': '#d4e3ff',
        'surface-container-highest': '#e0e3e5',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#00210c',
        'surface-container': '#eceef0',
        'surface': '#f7f9fb',
        'surface-variant': '#e0e3e5',
        'tertiary-container': '#0059a0',
        'tertiary': '#004178',
        'background': '#f7f9fb',
        'inverse-surface': '#2d3133',
        'on-surface': '#191c1e',
        'inverse-on-surface': '#eff1f3',
        'primary': '#003c90',
        'tertiary-fixed-dim': '#a4c9ff',
        'on-surface-variant': '#434653',
        'secondary-fixed-dim': '#4ae183',
        'on-primary-fixed': '#001945',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#c3c6d5',
        'outline': '#737784',
        'surface-container-low': '#f2f4f6',
        'secondary': '#006d37',
        'secondary-fixed': '#6bfe9c',
        'secondary-container': '#6bfe9c',
        'inverse-primary': '#b0c6ff',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#004883',
        'on-background': '#191c1e',
        'surface-bright': '#f7f9fb',
        'on-primary-container': '#bcceff',
        'surface-container-high': '#e6e8ea',
        'on-tertiary-container': '#b1d0ff',
        'primary-fixed-dim': '#b0c6ff',
        'surface-tint': '#1d59c1',
        'on-primary-fixed-variant': '#00419c',
        'on-tertiary': '#ffffff',
        'surface-dim': '#d8dadc',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#005228',
        'error': '#ba1a1a',
        'on-tertiary-fixed': '#001c39',
        'on-secondary-container': '#00743a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
      fontFamily: {
        'h1': ['Plus Jakarta Sans', 'sans-serif'],
        'h2': ['Plus Jakarta Sans', 'sans-serif'],
        'h3': ['Plus Jakarta Sans', 'sans-serif'],
        'label-caps': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'body-sm': ['Manrope', 'sans-serif'],
        'button': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'h1': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'button': ['16px', { lineHeight: '1', fontWeight: '600' }],
      },
      keyframes: {
        fadeIn: {
          'from': { opacity: '0', transform: 'translateY(12px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        spin: {
          'to': { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.4s ease-out',
      },
      backgroundImage: {
        'gradient-to-t-black': 'linear-gradient(to top, rgba(0,0,0,0.8), rgba(0,0,0,0.2), transparent)',
      },
    },
  },
  plugins: [],
} satisfies Config;
