import type { Config } from 'tailwindcss';

export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  safelist: [
    'bg-surface',
    'text-on-surface',
    'font-body-md',
    // Nature colors - blue
    'text-nature-blue-50',
    'text-nature-blue-100',
    'text-nature-blue-600',
    'text-nature-blue-700',
    'text-nature-blue-800',
    'text-nature-blue-900',
    'bg-nature-blue-50',
    'bg-nature-blue-100',
    'bg-nature-blue-600',
    'border-nature-blue-200',
    'border-nature-blue-300',
    // Nature colors - green
    'text-nature-green-300',
    'text-nature-green-600',
    'text-nature-green-700',
    'text-nature-green-800',
    'text-nature-green-900',
    'bg-nature-green-50',
    'bg-nature-green-100',
    'bg-nature-green-600',
    'border-nature-green-200',
    'border-nature-green-300',
    'hover:border-nature-green-300',
    // Nature colors - brown
    'text-nature-brown-400',
    'text-nature-brown-600',
    'text-nature-brown-700',
    'text-nature-brown-900',
    'bg-nature-brown-50',
    'bg-nature-brown-800',
    'bg-nature-brown-900',
    // Nature colors - amber
    'text-nature-amber-700',
    // Gradients
    'from-nature-blue-50',
    'from-nature-blue-600',
    'from-nature-blue-700',
    'from-nature-green-50',
    'from-nature-green-100',
    'from-nature-green-500',
    'from-nature-green-600',
    'from-nature-green-700',
    'from-nature-brown-900',
    'from-nature-amber-100',
    'to-nature-blue-50',
    'to-nature-blue-100',
    'to-nature-blue-600',
    'to-nature-green-50',
    'to-nature-green-100',
    'to-nature-green-600',
    'to-nature-green-700',
    'to-nature-brown-800',
    'via-nature-blue-50',
    'via-nature-brown-700',
    'via-nature-brown-800',
  ],
  theme: {
    extend: {
      colors: {
        // Natural Color Palette
        'nature-blue': {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c3d66',
        },
        'nature-green': {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#145231',
        },
        'nature-brown': {
          50: '#fafaf9',
          100: '#f5f5f0',
          200: '#e7e5e4',
          300: '#d6d3d1',
          400: '#a8a29e',
          500: '#78716c',
          600: '#57534e',
          700: '#44403c',
          800: '#292524',
          900: '#1c1917',
        },
        'nature-amber': {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        // Original colors for compatibility
        'on-secondary': '#ffffff',
        'primary-fixed': '#d9e2ff',
        'primary-container': '#0f52ba',
        'tertiary-fixed': '#d4e3ff',
        'surface-container-highest': '#e0e3e5',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#00210c',
        'surface-container': '#eceef0',
        'surface': '#f7f9fb',
        'surface-variant': '#e0e3e5',
        'tertiary-container': '#0059a0',
        'tertiary': '#004178',
        'background': '#f7f9fb',
        'inverse-surface': '#2d3133',
        'on-surface': '#191c1e',
        'inverse-on-surface': '#eff1f3',
        'primary': '#003c90',
        'tertiary-fixed-dim': '#a4c9ff',
        'on-surface-variant': '#434653',
        'secondary-fixed-dim': '#4ae183',
        'on-primary-fixed': '#001945',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#c3c6d5',
        'outline': '#737784',
        'surface-container-low': '#f2f4f6',
        'secondary': '#006d37',
        'secondary-fixed': '#6bfe9c',
        'secondary-container': '#6bfe9c',
        'inverse-primary': '#b0c6ff',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#004883',
        'on-background': '#191c1e',
        'surface-bright': '#f7f9fb',
        'on-primary-container': '#bcceff',
        'surface-container-high': '#e6e8ea',
        'on-tertiary-container': '#b1d0ff',
        'primary-fixed-dim': '#b0c6ff',
        'surface-tint': '#1d59c1',
        'on-primary-fixed-variant': '#00419c',
        'on-tertiary': '#ffffff',
        'surface-dim': '#d8dadc',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#005228',
        'error': '#ba1a1a',
        'on-tertiary-fixed': '#001c39',
        'on-secondary-container': '#00743a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
      fontFamily: {
        'h1': ['Plus Jakarta Sans', 'sans-serif'],
        'h2': ['Plus Jakarta Sans', 'sans-serif'],
        'h3': ['Plus Jakarta Sans', 'sans-serif'],
        'label-caps': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'body-sm': ['Manrope', 'sans-serif'],
        'button': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'h1': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'button': ['16px', { lineHeight: '1', fontWeight: '600' }],
      },
      keyframes: {
        fadeIn: {
          'from': { opacity: '0', transform: 'translateY(12px)' },
          'to': { opacity: '1', transform: 'translateY(0)' },
        },
        spin: {
          'to': { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.4s ease-out',
      },
      backgroundImage: {
        'gradient-to-t-black': 'linear-gradient(to top, rgba(0,0,0,0.8), rgba(0,0,0,0.2), transparent)',
      },
    },
  },
  plugins: [],
} satisfies Config;
